# Generated by Django 3.2.5 on 2021-08-01 10:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lucere_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='dateissued',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lucere_bot.event')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lucere_bot.user')),
            ],
        ),
    ]
